[Unit]
Description=Plasma login manager override for iMac A1419
After=graphical.target

[Service]
ExecStartPre=/usr/local/bin/wait-for-drm.sh
ExecStartPre=/usr/bin/sleep 10
Restart=on-failure
RestartSec=5
